### ISSUE TITLE
WPA handshakes

### ISSUE THREAD

**Issue by anudeepND** [pulkin/esp8266-injection-example#7]
Is it possible sniff WPA handshakes with esp8266?

**Comment by pulkin** [comment]
Sure, ESP can do that.

**Comment by pulkin** [comment]
Maybe someone will give an example on interfacing with [aircrack-ng](https://www.aircrack-ng.org) package?

**Comment by anudeepND** [comment]
No, it's not possible to sniff full handshake. As far as I know, you can sniff only 4 packets.

**Comment by mcr-ksh** [comment]
sorry to bother, but can you elaborate on this?
